version: "3.9"
services:
  theos-auth:
    container_name: theos-auth
    image: ghcr.io/theos-dns/auth:latest
    network_mode: host
    environment:
      - FORWARD_TO=forward-proxy
      - PORTS=443,8020-8030
      - DB_PATH=/root/app/auth/db/database.sqlite3
      - UPSTREAM=
    volumes:
      - ${PWD}/database-auth.sqlite3:/root/app/auth/db/database.sqlite3
      - allowedIps:/var/nginx

volumes:
  allowedIps: