services:
  theos-auth:
    container_name: theos-auth
    image: ghcr.io/theos-dns/auth:latest
    network_mode: host
    environment:
      - FORWARD_TO=forward-proxy
      - PORTS=443,8020-8030
      - DB_PATH=/root/app/auth/db/database.sqlite3
      - PROTECT=dns-server:53@53,coap:85@5688
      - UPSTREAM=
      - STARTUP_SLEEP=
      - RESOLVER=127.0.0.53:53
    volumes:
      - ${PWD}/database-auth.sqlite3:/root/app/auth/db/database.sqlite3
      - allowedIps:/var/nginx

volumes:
  allowedIps: